# Generated by Django 4.1.2 on 2022-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=200)),
                ('team2', models.CharField(max_length=200)),
                ('team3', models.CharField(max_length=200)),
                ('team4', models.CharField(max_length=200)),
                ('team5', models.CharField(max_length=200)),
                ('team6', models.CharField(max_length=200)),
                ('team7', models.CharField(max_length=200)),
                ('team8', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='AllPlayers',
            new_name='AllPlayer',
        ),
    ]
